# Generated by Django 6.0.8 on 2026-09-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_check_in_time_booking_checked_in_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
