# Generated by Django 6.0.8 on 2026-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resourcereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
