# Generated by Django 6.0.8 on 2026-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking_amount_paid_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dress_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='equipment_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='materials_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
